- name: Configuring {{COMPONENT}} Repository
  ansible.builtin.copy:
    src: redis.repo                                           # Location of the file on the machine where you're running this cript
    dest: /etc/yum.repos.d/redis.repo                       # Location of the file where you want to copy this to remote server.

- name: Installing {{COMPONENT}} package
  ansible.builtin.package:
    name: redis-6.2.13
    state: present 

- name: Enabling {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enabling {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}" 
    state: started
    enabled: yes
    daemon_reload: yes

