- name: Installing Maven
  ansible.builtin.shell: curl https://gitlab.com/thecloudcareers/opensource/-/raw/master/lab-tools/maven-java11/install.sh | bash 

- name: Creating {{APPUSER}} account
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: Download and extracting {{COMPONENT}} Schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp 
    remote_src: yes  

- name: Performing {{COMPONENT}} cleanup 
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent 

- name: Copying {{COMPONENT}} to {{APPUSER}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes 

- name: Generating {{COMPONENT}} Artifacts
  ansible.builtin.shell: mvn clean package &&  mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copying {{COMPONENT}} systemd file 
  ansible.builtin.template:
    src: systemd.service               
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
