- name: Installing ERLANG
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Configuring {{COMPONENT}} repository 
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: rabbitmq-server 
    state: present 

- name: Starting {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Creting {{APPUSER}} user 
  community.rabbitmq.rabbitmq_user:
    user: roboshop 
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present