- name: Copying Logstash Config
  ansible.builtin.template:
    src: logstash.conf                 
    dest: /etc/logstash/conf.d/logstash.conf                   

- name: Restarting Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Wait for logstash to come up 
  ansible.builtin.wait_for:
    port: 5044
    delay: 30 
    timeout: 60

# Any change that you make to logStash would need a restart