- name: Configuring {{COMPONENT}} Repository
  ansible.builtin.copy:
    src: mysql.repo                                           # Location of the file on the machine where you're running this cript
    dest: /etc/yum.repos.d/mysql.repo                       # Location of the file where you want to copy this to remote server.

- name: Installing {{COMPONENT}} package
  ansible.builtin.package:
    name: mysql-community-server
    state: present 

- name: Starting {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: mysqld  
    state: started
    enabled: yes

- name: Extracting the mysql log file
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: psw_log 

- name: Pritning the password file 
  debug:
    msg: "{{pws_log}}"

# - name: Extracing the password from logFile  
#   ansible.builtin.set_fact:
#     DEFAULT_PASSWORD: "{{ psw_log['content'] }}"
  