- name: Configuring {{COMPONENT}} Repository
  ansible.builtin.copy:
    src: mysql.repo                                           # Location of the file on the machine where you're running this cript
    dest: /etc/yum.repos.d/mysql.repo                       # Location of the file where you want to copy this to remote server.

- name: Installing {{COMPONENT}} package
  ansible.builtin.package:
    name: mysql-community-server
    state: present 