- name: Copying Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml              
    dest: /opt/prometheus/prometheus.yml                 

- name: Restarting Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Wait for Prometheus to come up 
  ansible.builtin.wait_for:
    port: 9090
    delay: 10 
    timeout: 30