- name: Installing Python
  ansible.builtin.package:
    name: 
      - python36 
      - gcc 
      - python3-devel 
    state: present  

- name: Creating User Account 
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Downloading Artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract