global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  static_configs:
    - targets: ["localhost:9090"]

- job_name: service_discovery 
  ec2_sd_configs: 
    - region: us-east-1
      port: 9100